package br.com.projeto.GUI;

import br.com.projeto.conexao.ConexaoBanco;
import br.com.projeto.entidades.Funcionario;
import br.com.projeto.interfaces.FuncionarioDao;
import br.com.projeto.interfacesImpl.FuncionarioDaoImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rafael Cardozo
 */
public class AlterarSenhaDoFuncionarioLogin extends javax.swing.JFrame {

    /**
     * Creates new form SenhaFun
     */
    public AlterarSenhaDoFuncionarioLogin() {
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        avisos = new javax.swing.JTextPane();
        confirmar = new javax.swing.JToggleButton();
        senhaNova = new javax.swing.JPasswordField();
        repetirSenha = new javax.swing.JPasswordField();
        cpf = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        voltar = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magnoteca");
        setResizable(false);
        getContentPane().setLayout(null);

        avisos.setForeground(new java.awt.Color(255, 0, 0));
        avisos.setCaretColor(new java.awt.Color(255, 0, 0));
        avisos.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        avisos.setFocusCycleRoot(false);
        avisos.setFocusable(false);
        jScrollPane3.setViewportView(avisos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 140, 110);

        confirmar.setFont(new java.awt.Font("Centaur", 0, 11)); // NOI18N
        confirmar.setText("Alterar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(488, 407, 76, 34);
        getContentPane().add(senhaNova);
        senhaNova.setBounds(250, 240, 220, 30);

        repetirSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                repetirSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(repetirSenha);
        repetirSenha.setBounds(250, 280, 220, 30);

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        try {
            javax.swing.text.MaskFormatter cpfx = new javax.swing.text.MaskFormatter("###.###.###-##");
            cpf = new javax.swing.JFormattedTextField(cpfx);
        }catch(Exception e){
            System.exit(1);
        }
        getContentPane().add(cpf);
        cpf.setBounds(250, 200, 220, 30);

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(250, 160, 220, 30);

        voltar.setFont(new java.awt.Font("Centaur", 1, 11)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(570, 407, 76, 34);

        jLabel5.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel5.setText("Repetir nova senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 280, 170, 24);

        jLabel4.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel4.setText("Nova senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 240, 150, 24);

        jLabel3.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel3.setText("C.P.F:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 200, 100, 24);

        jLabel2.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel2.setText("Nome de usuário:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 150, 24);

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel1.setText("ALTERAR SENHA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(261, 70, 200, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 0, 85, 290);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 379, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String cpfV = cpf.getText();
        String usuarioV = usuario.getText();
        char[] senhaNovaChar = senhaNova.getPassword();
        String senhaNovaV = new String(senhaNovaChar);
        char[] senhaRepetirChar = repetirSenha.getPassword();
        String senhaRepetirV = new String(senhaRepetirChar);

        if (!senhaNovaV.equals(senhaRepetirV)) {
            avisos.setText(avisos.getText() + " - As Senhas não conferem\n");

        }
        if ((senhaNovaV.length() < 5) || (senhaNovaV.length() > 8)) {
            avisos.setText(avisos.getText() + "- Utilize no mínimo 5 e no máximo 8 caracteres para a senha\n");
        }

        Funcionario funcionario = null;
        FuncionarioDao funcionarioDao = new FuncionarioDaoImpl(ConexaoBanco.getConnection());
        funcionario = funcionarioDao.buscarTudoFuncionario(usuarioV);
        try {
            ConexaoBanco.getConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(AlterarSenhaDoFuncionarioLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        funcionario.setUsuario(usuarioV);

        boolean updateCorreto = false;
        if (funcionario == null) {
            avisos.setText("Seu nome de usuario está incorreto!");
        } else {
            if (senhaNovaV.equals(senhaRepetirV)) {
                if (funcionario.getCpf().equals(cpfV)) {
                    funcionario.setSenha(senhaNovaV);
                    updateCorreto = funcionarioDao.alterarDados(funcionario);
                    try {
                        ConexaoBanco.getConnection().commit();
                    } catch (SQLException ex) {
                        Logger.getLogger(AlterarSenhaDoClienteLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }

        if (updateCorreto) {
            JOptionPane.showMessageDialog(this, "Alteração realizada com sucesso!");
            dispose();
        }


    }//GEN-LAST:event_confirmarActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void repetirSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repetirSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_repetirSenhaKeyPressed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane avisos;
    private javax.swing.JToggleButton confirmar;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPasswordField repetirSenha;
    private javax.swing.JPasswordField senhaNova;
    private javax.swing.JTextField usuario;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
}
