package br.com.projeto.GUI;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 20121164010538
 */
public class ClienteDataDeDevolucao extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public ClienteDataDeDevolucao() {
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Erro", 0);
        }        
        setSize(678, 489);
        String dataV = RealizarNovoEmprestimo.DE; 
        data.setText(dataV);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new javax.swing.JLabel();
        confirmar = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magnoteca");
        setMinimumSize(new java.awt.Dimension(678, 492));
        setResizable(false);
        getContentPane().setLayout(null);

        data.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        String emprestimo = br.com.projeto.GUI.RealizarNovoEmprestimo.DE;
        data.setText(emprestimo);
        getContentPane().add(data);
        data.setBounds(70, 60, 460, 280);

        confirmar.setText("Ok!");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmarKeyPressed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(570, 400, 70, 31);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, -10, 85, 290);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        try {
            new PaginaDeAcessoFuncionario().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_confirmarActionPerformed

    private void confirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            confirmar.doClick();
        }
    }//GEN-LAST:event_confirmarKeyPressed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton confirmar;
    private static javax.swing.JLabel data;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
