package br.com.projeto.GUI;

import br.com.projeto.conexao.ConexaoBanco;
import br.com.projeto.entidades.Cliente;
import br.com.projeto.interfaces.ClienteDao;
import br.com.projeto.interfacesImpl.ClienteDaoImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rafael Cardozo
 */
public class LoginCliente extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public LoginCliente() {
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        esqueceuSenha = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        aviso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Magnoteca");
        setResizable(false);
        getContentPane().setLayout(null);

        esqueceuSenha.setText("Esqueceu sua senha?");
        esqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqueceuSenhaActionPerformed(evt);
            }
        });
        esqueceuSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                esqueceuSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(esqueceuSenha);
        esqueceuSenha.setBounds(470, 390, 180, 34);

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel1.setText("CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 50, 160, 50);

        jLabel2.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 120, 80, 40);

        jLabel3.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 160, 90, 40);

        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(210, 130, 220, 30);

        confirmar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmarKeyPressed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(220, 240, 102, 39);

        cancelar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelarKeyPressed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(330, 240, 102, 39);

        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(210, 170, 220, 30);

        aviso.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(aviso);
        aviso.setBounds(210, 210, 212, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, -10, 85, 290);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String usuarioV = login.getText().trim();
        char[] senha1 = senha.getPassword();
        String senhaCorreta = new String(senha1);
        if (usuarioV.equals("") || senhaCorreta.equals("")) {
            aviso.setText("Digite seu nome de usuário e sua senha!");
        }
        Cliente cliente = new Cliente(usuarioV, senhaCorreta);
        ClienteDao clienteDaoImpl = new ClienteDaoImpl(ConexaoBanco.getConnection());
        String senhaBanco = clienteDaoImpl.buscarSenha(cliente);
        try {
            ConexaoBanco.getConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(LoginFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (senhaBanco == null) {
            aviso.setText("Nome de usuario incorreto!");
        } else {
            if (senhaBanco.equals(senhaCorreta)) {
                Cliente cliente2 = clienteDaoImpl.buscarTudoCliente(usuarioV);
                try {
                    ConexaoBanco.getConnection().commit();
                } catch (SQLException ex) {
                    Logger.getLogger(LoginFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
                cliente2.setUsuario(usuarioV);
                new PaginaDeAcessoCliente(cliente2).setVisible(true);
                dispose();
            } else {
                aviso.setText("Senha Incorreta!");
            }
        }


    }//GEN-LAST:event_confirmarActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {
            new LoginCliente().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void esqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqueceuSenhaActionPerformed
        new AlterarSenhaDoClienteLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_esqueceuSenhaActionPerformed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_senhaKeyPressed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void confirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_confirmarKeyPressed

    private void cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_cancelarKeyPressed

    private void esqueceuSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esqueceuSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_esqueceuSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JToggleButton esqueceuSenha;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
