package br.com.projeto.GUI;

import br.com.projeto.conexao.ConexaoBanco;
import br.com.projeto.entidades.Funcionario;
import br.com.projeto.interfaces.FuncionarioDao;
import br.com.projeto.interfacesImpl.FuncionarioDaoImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rafael Cardozo
 */
public class LoginFuncionario extends javax.swing.JFrame {

    public LoginFuncionario() {
        initComponents();

        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        novoCadastro = new javax.swing.JButton();
        login = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        esqueceuSenha = new javax.swing.JToggleButton();
        Nome = new javax.swing.JLabel();
        aviso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Magnoteca");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel1.setText("FUNCIONÁRIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 40, 190, 60);

        novoCadastro.setFont(new java.awt.Font("Centaur", 0, 12)); // NOI18N
        novoCadastro.setText("Novo Cadastro");
        novoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCadastroActionPerformed(evt);
            }
        });
        novoCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                novoCadastroKeyPressed(evt);
            }
        });
        getContentPane().add(novoCadastro);
        novoCadastro.setBounds(520, 400, 104, 34);

        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(200, 120, 214, 30);

        confirmar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmarKeyPressed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(200, 250, 102, 39);

        cancelar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelarKeyPressed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(310, 250, 102, 39);

        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(200, 170, 214, 30);

        esqueceuSenha.setText("Esqueceu sua senha?");
        esqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqueceuSenhaActionPerformed(evt);
            }
        });
        esqueceuSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                esqueceuSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(esqueceuSenha);
        esqueceuSenha.setBounds(350, 400, 160, 34);
        getContentPane().add(Nome);
        Nome.setBounds(371, 0, 31, 21);

        aviso.setForeground(new java.awt.Color(255, 0, 0));
        aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(aviso);
        aviso.setBounds(200, 210, 214, 20);

        jLabel2.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 120, 80, 40);

        jLabel3.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 160, 90, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, -10, 85, 290);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed
    public static String usuario = null;
    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String usuarioV = login.getText().trim();
        char[] senha1 = senha.getPassword();
        String senhaCorreta = new String(senha1);
        if (usuarioV.equals("") || senhaCorreta.equals("")) {
            aviso.setText("Digite seu nome de usuário e sua senha!");
        }
        
        Funcionario funcionario = new Funcionario(usuarioV, senhaCorreta);
        FuncionarioDao funcionarioDaoImpl = new FuncionarioDaoImpl(ConexaoBanco.getConnection());
        Funcionario funcionario2 = funcionarioDaoImpl.buscarSenha(funcionario);
        try {
            ConexaoBanco.getConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(LoginFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (funcionario2.getSenha() == null) {
            aviso.setText("Seu nome de usuario está incorreto!");
        } else {
            if (funcionario2.getSenha().equals(senhaCorreta)) {
                if (funcionario2.getBibliotecario() == 1) {
                    Funcionario funcionarioB = funcionarioDaoImpl.buscarTudoFuncionario(usuarioV);
                    try {
                        ConexaoBanco.getConnection().commit();
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    funcionarioB.setUsuario(usuarioV);
                    new PaginaDeAcessoFuncionarioBibliotecario(funcionarioB).setVisible(true);
                    dispose();
                }
                if (funcionario2.getBibliotecario() == 0) {
                    Funcionario funcionarioNB = funcionarioDaoImpl.buscarTudoFuncionario(usuarioV);
                    try {
                        ConexaoBanco.getConnection().commit();
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    funcionarioNB.setUsuario(usuarioV);
                    new PaginaDeAcessoFuncionario(funcionarioNB).setVisible(true);
                    dispose();
                }
            } else {
                aviso.setText("Sua senha está incorreta!");
            }
        }


    }//GEN-LAST:event_confirmarActionPerformed
    private void novoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCadastroActionPerformed
        new CadastrarNovoFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_novoCadastroActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void confirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmarKeyPressed
        /*if(evt.getKeyCode() != KeyEvent.VK_ENTER){ 
         try{
         new FuncionarioLogin().setVisible(true);
            
         catch(Exeption e){
            
         }
         }
            
         dispose();
            
       
         }*/
    }//GEN-LAST:event_confirmarKeyPressed

    private void esqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqueceuSenhaActionPerformed
        new AlterarSenhaDoFuncionarioLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_esqueceuSenhaActionPerformed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_senhaKeyPressed

    private void cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_cancelarKeyPressed

    private void esqueceuSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esqueceuSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_esqueceuSenhaKeyPressed

    private void novoCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_novoCadastroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_novoCadastroKeyPressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel aviso;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JToggleButton esqueceuSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField login;
    private javax.swing.JButton novoCadastro;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables

    public String getNome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getCpf() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getRg() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Date getDataNasc() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public int getIdEndereco() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public int getIdContato() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getSenha() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
