package br.com.projeto.GUI;

import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafael Cardozo
 */

public class PaginaInicial extends javax.swing.JFrame {
    /**
     * Creates new form Inicio
     */
    public PaginaInicial() {          
        initComponents();                
    
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("\\Imagens\\icon.png");
            setIconImage(icon);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Erro", 0);
        }
        setSize(960, 630);
     
        setExtendedState(PaginaInicial.MAXIMIZED_BOTH);
        
        this.getContentPane().setBackground(Color.WHITE);
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        pesquisaJ = new javax.swing.JLabel();
        funcionarioJ = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clienteJ = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sairJ = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setTitle("Magnoteca");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador7.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(810, -80, 70, 400);

        pesquisaJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        pesquisaJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisaJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaJMouseExited(evt);
            }
        });
        getContentPane().add(pesquisaJ);
        pesquisaJ.setBounds(730, -140, 70, 580);

        funcionarioJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        funcionarioJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionarioJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionarioJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funcionarioJMouseExited(evt);
            }
        });
        getContentPane().add(funcionarioJ);
        funcionarioJ.setBounds(650, -100, 67, 580);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador4.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1370, -110, 70, 410);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcardor3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, -20, 70, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador4.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(890, -20, 70, 391);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcardor2.1BG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 440, 671, 300);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcardor3.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1050, -20, 70, 420);

        clienteJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        clienteJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clienteJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clienteJMouseExited(evt);
            }
        });
        getContentPane().add(clienteJ);
        clienteJ.setBounds(570, -200, 70, 580);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/marcadoriscadoPNG2.1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, -110, 70, 400);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador7.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, -70, 70, 400);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/marcadoriscadoPNG3.1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, -130, 70, 410);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador10.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 70, 390);

        sairJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        sairJ.setDoubleBuffered(true);
        sairJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairJMouseExited(evt);
            }
        });
        getContentPane().add(sairJ);
        sairJ.setBounds(490, -260, 70, 600);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador7.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1130, -50, 70, 400);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/marcadoriscadoPNG3.1.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1210, -70, 70, 410);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador10.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(1290, 0, 70, 390);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/marcadoriscadoPNG2.1.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(970, -100, 70, 400);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Marcador4.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(250, -10, 70, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteJMouseClicked
        new LoginCliente().setVisible(true);
    }//GEN-LAST:event_clienteJMouseClicked

    private void clienteJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteJMouseExited
        this.clienteJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/cliente.png")));
       
    }//GEN-LAST:event_clienteJMouseExited

    private void funcionarioJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioJMouseClicked
        new LoginFuncionario().setVisible(true);
    }//GEN-LAST:event_funcionarioJMouseClicked

    private void pesquisaJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaJMouseClicked
        new PesquisaDeLivros().setVisible(true);
    }//GEN-LAST:event_pesquisaJMouseClicked

    private void sairJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairJMouseClicked
        System.exit(0);
    }//GEN-LAST:event_sairJMouseClicked

    private void clienteJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteJMouseEntered
        /*ImageIcon novaImagem = new ImageIcon("/Imagens/marcarcliente.png");
        clienteJ.setIcon((novaImagem));*/
        this.clienteJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/marcadorcliente1.png")));        
        //getContentPane().add(clienteJ);
        clienteJ.setVisible(true);
      
    }//GEN-LAST:event_clienteJMouseEntered

    private void sairJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairJMouseEntered
        this.sairJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/marcadorsair1.png")));
        
    }//GEN-LAST:event_sairJMouseEntered

    private void sairJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairJMouseExited
        this.sairJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/sair.png")));
        
    }//GEN-LAST:event_sairJMouseExited

    private void funcionarioJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioJMouseEntered
        this.funcionarioJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/marcadorfuncionario1.png")));
     
    }//GEN-LAST:event_funcionarioJMouseEntered

    private void funcionarioJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioJMouseExited
        this.funcionarioJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/funcionario.png")));
        
    }//GEN-LAST:event_funcionarioJMouseExited

    private void pesquisaJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaJMouseEntered
        this.pesquisaJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/marcadorpesquisa1.png")));
        
    }//GEN-LAST:event_pesquisaJMouseEntered

    private void pesquisaJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaJMouseExited
        this.pesquisaJ.setIcon(new ImageIcon(getClass().getResource("/Imagens/pesquisa.png")));
        
    }//GEN-LAST:event_pesquisaJMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
        Random r = new Random();
        if (!new File("Codigo.txt").exists()){
            int codigo = r.nextInt();
            while (codigo < 1000 || codigo > 10000){
                codigo = r.nextInt(10000);
            }
            String cod = String.valueOf(codigo);
            
            File f3 = new File("Codigo.txt");
            try (FileWriter fw = new FileWriter(f3); BufferedWriter bw = new BufferedWriter(fw)) {
                bw.write(cod);
            }
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clienteJ;
    private javax.swing.JLabel funcionarioJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel pesquisaJ;
    private javax.swing.JLabel sairJ;
    // End of variables declaration//GEN-END:variables
}
