package br.com.projeto.GUI;

import br.com.projeto.entidades.Cliente;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rafael Cardozo
 */
public class PaginaDeAcessoCliente extends javax.swing.JFrame {

    private Cliente umCliente = null;

    /**
     * Creates new form Clientes2
     */
    public PaginaDeAcessoCliente(Cliente umCliente) {
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }

        setSize(736, 489);
        this.getContentPane().setBackground(Color.WHITE);

        this.umCliente = umCliente;
        bv.setText("Bem vindo, " + this.umCliente.getNome());

        this.setLocationRelativeTo(null);
    }

    public PaginaDeAcessoCliente() {
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }

        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bv = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        situacao = new javax.swing.JLabel();
        dados = new javax.swing.JLabel();
        historico = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Magnoteca");
        setMinimumSize(new java.awt.Dimension(678, 492));
        setResizable(false);
        getContentPane().setLayout(null);

        bv.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        bv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bv.setText("BEM VINDO");
        bv.setToolTipText("");
        getContentPane().add(bv);
        bv.setBounds(20, 60, 580, 30);

        voltar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                voltarKeyPressed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(610, 380, 76, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        situacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btsituação.png"))); // NOI18N
        situacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                situacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                situacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                situacaoMouseExited(evt);
            }
        });
        getContentPane().add(situacao);
        situacao.setBounds(100, 170, 160, 120);

        dados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btdados.png"))); // NOI18N
        dados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dadosMouseExited(evt);
            }
        });
        getContentPane().add(dados);
        dados.setBounds(270, 180, 160, 100);

        historico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bthistórico.png"))); // NOI18N
        historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historicoMouseExited(evt);
            }
        });
        getContentPane().add(historico);
        historico.setBounds(440, 170, 160, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, -10, 85, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        try {
            new LoginCliente().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void voltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voltarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            voltar.doClick();
        }
    }//GEN-LAST:event_voltarKeyPressed

    private void situacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_situacaoMouseClicked
        new ClienteSituacao(this.umCliente).setVisible(true);
    }//GEN-LAST:event_situacaoMouseClicked

    private void dadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosMouseClicked
        new VisualizarDadosCliente(this.umCliente).setVisible(true);
        dispose();
    }//GEN-LAST:event_dadosMouseClicked

    private void historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historicoMouseClicked
        new ClienteHistorico(this.umCliente).setVisible(true);
    }//GEN-LAST:event_historicoMouseClicked

    private void situacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_situacaoMouseEntered
        this.situacao.setIcon(new ImageIcon(getClass().getResource("/Imagens/btsituaçãoover.jpg")));
    }//GEN-LAST:event_situacaoMouseEntered

    private void situacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_situacaoMouseExited
        this.situacao.setIcon(new ImageIcon(getClass().getResource("/Imagens/btsituação.png")));
    }//GEN-LAST:event_situacaoMouseExited

    private void dadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosMouseEntered
        this.dados.setIcon(new ImageIcon(getClass().getResource("/Imagens/btdadosover.jpg")));
    }//GEN-LAST:event_dadosMouseEntered

    private void dadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosMouseExited
        this.dados.setIcon(new ImageIcon(getClass().getResource("/Imagens/btdados.png")));
    }//GEN-LAST:event_dadosMouseExited

    private void historicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historicoMouseEntered
        this.historico.setIcon(new ImageIcon(getClass().getResource("/Imagens/bthistóricoover.jpg")));
    }//GEN-LAST:event_historicoMouseEntered

    private void historicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historicoMouseExited
        this.historico.setIcon(new ImageIcon(getClass().getResource("/Imagens/bthistórico.png")));
    }//GEN-LAST:event_historicoMouseExited

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bv;
    private javax.swing.JLabel dados;
    private javax.swing.JLabel historico;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel situacao;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
