/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.projeto.GUI;

import br.com.projeto.entidades.Funcionario;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 20121164010538
 */
public class PaginaDeAcessoFuncionarioBibliotecario extends javax.swing.JFrame {
    
    private Funcionario umFuncionario;
    /**
     * Creates new form PaginaDeAcessoFuncionarioBibliotecario
     */
    public PaginaDeAcessoFuncionarioBibliotecario(Funcionario umFuncionario){
        initComponents();
        
        setSize(729, 489);
        this.getContentPane().setBackground(Color.WHITE);
        this.umFuncionario = umFuncionario;
        
        bv.setText("Bem vindo, " + this.umFuncionario.getNome());
        
        this.setLocationRelativeTo(null);  
    }
    
    public PaginaDeAcessoFuncionarioBibliotecario(){
        initComponents();
        
        
        this.getContentPane().setBackground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        bv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        devolucao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emprestimo = new javax.swing.JLabel();
        pesquisa = new javax.swing.JLabel();
        adicionarcliente = new javax.swing.JLabel();
        adiconarlivros = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        voltar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                voltarKeyPressed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(600, 390, 76, 34);

        bv.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        bv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bv.setText("BEM VINDO");
        bv.setToolTipText("");
        getContentPane().add(bv);
        bv.setBounds(50, 20, 580, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        devolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btdevolução.png"))); // NOI18N
        devolucao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devolucaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                devolucaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                devolucaoMouseExited(evt);
            }
        });
        getContentPane().add(devolucao);
        devolucao.setBounds(260, 90, 160, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btdados.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 250, 130, 100);

        emprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btemprestimo.png"))); // NOI18N
        emprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emprestimoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emprestimoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emprestimoMouseExited(evt);
            }
        });
        getContentPane().add(emprestimo);
        emprestimo.setBounds(430, 100, 180, 100);

        pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btpesquisa.png"))); // NOI18N
        pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaMouseExited(evt);
            }
        });
        getContentPane().add(pesquisa);
        pesquisa.setBounds(280, 230, 140, 140);

        adicionarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btadicionarcliente.png"))); // NOI18N
        adicionarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarclienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adicionarclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adicionarclienteMouseExited(evt);
            }
        });
        getContentPane().add(adicionarcliente);
        adicionarcliente.setBounds(430, 250, 150, 100);

        adiconarlivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btadicionarlivros.png"))); // NOI18N
        adiconarlivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adiconarlivrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adiconarlivrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adiconarlivrosMouseExited(evt);
            }
        });
        getContentPane().add(adiconarlivros);
        adiconarlivros.setBounds(80, 80, 170, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, -20, 85, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        try {
            new LoginFuncionario().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Algo saiu errado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void voltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voltarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            voltar.doClick();
        }
    }//GEN-LAST:event_voltarKeyPressed

    private void adiconarlivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adiconarlivrosMouseClicked
        new CadastrarNovoItemNoAcervo().setVisible(true);
    }//GEN-LAST:event_adiconarlivrosMouseClicked

    private void devolucaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucaoMouseClicked
        new RealizarDevolucaoBibliotecario().setVisible(true);
    }//GEN-LAST:event_devolucaoMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new VisualizarDadosFuncionarioBibliotecario(this.umFuncionario).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void emprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimoMouseClicked
       new RealizarNovoEmprestimoBibliotecario().setVisible(true);
    }//GEN-LAST:event_emprestimoMouseClicked

    private void pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaMouseClicked
        new PesquisaDeLivroParaClienteBibliotecario().setVisible(true);
    }//GEN-LAST:event_pesquisaMouseClicked

    private void adicionarclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarclienteMouseClicked
        new CadastrarNovoClienteBibliotecario().setVisible(true);
    }//GEN-LAST:event_adicionarclienteMouseClicked

    private void adicionarclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarclienteMouseEntered
        this.adicionarcliente.setIcon(new ImageIcon(getClass().getResource("/Imagens/btadicionarclienteover.jpg")));
    }//GEN-LAST:event_adicionarclienteMouseEntered

    private void adicionarclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarclienteMouseExited
       this.adicionarcliente.setIcon(new ImageIcon(getClass().getResource("/Imagens/btadicionarcliente.png")));
    }//GEN-LAST:event_adicionarclienteMouseExited

    private void adiconarlivrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adiconarlivrosMouseEntered
        this.adiconarlivros.setIcon(new ImageIcon(getClass().getResource("/Imagens/btadicionarlivrosover.jpg")));
    }//GEN-LAST:event_adiconarlivrosMouseEntered

    private void adiconarlivrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adiconarlivrosMouseExited
        this.adiconarlivros.setIcon(new ImageIcon(getClass().getResource("/Imagens/btadicionarlivros.png")));
    }//GEN-LAST:event_adiconarlivrosMouseExited

    private void devolucaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucaoMouseEntered
        this.devolucao.setIcon(new ImageIcon(getClass().getResource("/Imagens/btdevoluçãoover.jpg")));
    }//GEN-LAST:event_devolucaoMouseEntered

    private void devolucaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucaoMouseExited
        this.devolucao.setIcon(new ImageIcon(getClass().getResource("/Imagens/btdevolução.png")));
    }//GEN-LAST:event_devolucaoMouseExited

    private void emprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimoMouseEntered
        this.emprestimo.setIcon(new ImageIcon(getClass().getResource("/Imagens/btemprestimoover.jpg")));
    }//GEN-LAST:event_emprestimoMouseEntered

    private void emprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimoMouseExited
        this.emprestimo.setIcon(new ImageIcon(getClass().getResource("/Imagens/btemprestimo.png")));
    }//GEN-LAST:event_emprestimoMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("/Imagens/btdadosover.jpg")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("/Imagens/btdados.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void pesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaMouseEntered
        this.pesquisa.setIcon(new ImageIcon(getClass().getResource("/Imagens/btpesquisaover.jpg")));
    }//GEN-LAST:event_pesquisaMouseEntered

    private void pesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaMouseExited
       this.pesquisa.setIcon(new ImageIcon(getClass().getResource("/Imagens/btpesquisa.png")));
    }//GEN-LAST:event_pesquisaMouseExited

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionarcliente;
    private javax.swing.JLabel adiconarlivros;
    private javax.swing.JLabel bv;
    private javax.swing.JLabel devolucao;
    private javax.swing.JLabel emprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pesquisa;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
