package br.com.projeto.GUI;

import br.com.projeto.conexao.ConexaoBanco;
import br.com.projeto.entidades.Cliente;
import br.com.projeto.entidades.Emprestimo;
import br.com.projeto.entidades.Livro;
import br.com.projeto.interfaces.EmprestimoDao;
import br.com.projeto.interfacesImpl.AcervoDaoImpl;
import br.com.projeto.interfacesImpl.ClienteDaoImpl;
import br.com.projeto.interfacesImpl.EmprestimoDaoImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.ImageObserver;
import java.sql.Date;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tainara Lima
 */
public class RealizarNovoEmprestimo extends javax.swing.JFrame {

    public static String DE;

    /**
     * Creates new form NovoEmprestimo
     */
    public boolean a;
    public boolean b;

    public RealizarNovoEmprestimo() {
        initComponents();

        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dia = new javax.swing.JComboBox();
        mes = new javax.swing.JComboBox();
        ano = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        nomedolivro = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        nomedousuario = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        avisos = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        previsaoEntrega = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Magnoteca");
        getContentPane().setLayout(null);

        dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diaKeyPressed(evt);
            }
        });
        getContentPane().add(dia);
        dia.setBounds(280, 290, 60, 30);

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"}));
        mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mesKeyPressed(evt);
            }
        });
        getContentPane().add(mes);
        mes.setBounds(340, 290, 60, 30);

        ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913" }));
        ano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                anoKeyPressed(evt);
            }
        });
        getContentPane().add(ano);
        ano.setBounds(400, 290, 100, 30);

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel1.setText("EMPRÉSTIMO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 100, 230, 22);

        jLabel2.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel2.setText("Nome do usuário (Cliente):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 230, 24);

        jLabel3.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel3.setText("Nome do livro:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 250, 140, 24);

        jLabel5.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel5.setText("Data do empréstimo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 290, 190, 24);

        Senha.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        Senha.setText("Senha (Cliente):");
        getContentPane().add(Senha);
        Senha.setBounds(130, 210, 160, 24);
        getContentPane().add(nomedolivro);
        nomedolivro.setBounds(280, 250, 220, 30);
        getContentPane().add(senha);
        senha.setBounds(280, 210, 220, 30);

        nomedousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomedousuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nomedousuario);
        nomedousuario.setBounds(280, 170, 220, 30);

        confirmar.setFont(new java.awt.Font("Centaur", 0, 11)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(470, 410, 76, 34);

        cancelar.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(570, 410, 76, 34);

        avisos.setForeground(new java.awt.Color(255, 0, 0));
        avisos.setCaretColor(new java.awt.Color(255, 0, 0));
        avisos.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        avisos.setFocusCycleRoot(false);
        avisos.setFocusable(false);
        jScrollPane3.setViewportView(avisos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 10, 140, 120);

        jLabel6.setFont(new java.awt.Font("Linux Libertine G", 0, 18)); // NOI18N
        jLabel6.setText("Previsão de entrega:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 330, 190, 30);
        getContentPane().add(previsaoEntrega);
        previsaoEntrega.setBounds(280, 334, 230, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(550, -10, 85, 290);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 380, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String nomeCliente = nomedousuario.getText();
        char[] senhaClienteChar = senha.getPassword();
        String senhaCliente = String.copyValueOf(senhaClienteChar);
        String nomeLivro = nomedolivro.getText();

        String diaE = (String) dia.getSelectedItem();
        String mesE = (String) mes.getSelectedItem();
        String anoE = (String) ano.getSelectedItem();

        int dayOfMonth = Integer.parseInt(diaE);
        int month = Integer.parseInt(mesE);
        int year = Integer.parseInt(anoE);

        Calendar calendar = new GregorianCalendar(year, month, dayOfMonth);
        java.util.Date dataHojeDate = calendar.getTime();
        Date dataHoje = new Date(dataHojeDate.getTime());
        calendar.add(Calendar.DAY_OF_MONTH, +15);
        java.util.Date previsaoDevolucaoDate = calendar.getTime();
        Date previsaoDevolucao = new Date(previsaoDevolucaoDate.getTime());

        previsaoEntrega.setText(dayOfMonth + 15 + "-" + month + "-" + year);

        Livro livro = new Livro(nomeLivro);
        AcervoDaoImpl livroDaoImpl = new AcervoDaoImpl(ConexaoBanco.getConnection());
        livro.setId(livroDaoImpl.buscarId(livro));

        Cliente cliente = new Cliente(nomeCliente, senhaCliente);
        ClienteDaoImpl clienteDaoImpl = new ClienteDaoImpl(ConexaoBanco.getConnection());
        cliente.setId(clienteDaoImpl.buscarId(cliente));

        Emprestimo emprestimo = new Emprestimo(dataHoje, previsaoDevolucao, livro, cliente);
        EmprestimoDao emprestimoDao = new EmprestimoDaoImpl(ConexaoBanco.getConnection());
        int idEmprestimo = emprestimoDao.persistir(emprestimo);
        try {
            JOptionPane.showMessageDialog(this, "Emprestimo realizado com sucesso!");
            ConexaoBanco.getConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(RealizarNovoEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
            try {
                ConexaoBanco.getConnection().rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(RealizarNovoEmprestimo.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }

    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void diaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_diaKeyPressed

    private void mesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_mesKeyPressed

    private void anoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmar.doClick();
        }
    }//GEN-LAST:event_anoKeyPressed

    private void nomedousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomedousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomedousuarioActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Senha;
    private javax.swing.JComboBox ano;
    private javax.swing.JTextPane avisos;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JComboBox dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox mes;
    private javax.swing.JTextField nomedolivro;
    private javax.swing.JTextField nomedousuario;
    private javax.swing.JLabel previsaoEntrega;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
