package br.com.projeto.GUI;


import br.com.projeto.conexao.ConexaoBanco;
import br.com.projeto.entidades.Cliente;
import br.com.projeto.interfaces.ClienteDao;
import br.com.projeto.interfaces.ContatoDao;
import br.com.projeto.interfacesImpl.ClienteDaoImpl;
import br.com.projeto.interfacesImpl.ContatoDaoImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafael Cardozo
 */
public class VisualizarDadosCliente extends javax.swing.JFrame {
    private String nomedousuario;
    private Cliente umCliente;
    /**
     * Creates new form DadosCli
     */
    public VisualizarDadosCliente(Cliente umCliente){
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
        this.umCliente = umCliente;
        
        ClienteDao clienteDao = new ClienteDaoImpl(ConexaoBanco.getConnection());
        Cliente cliente2 = clienteDao.buscarTudoCliente(this.umCliente.getUsuario());
        ContatoDao contatoDao = new ContatoDaoImpl(ConexaoBanco.getConnection());
        String emailV = contatoDao.buscarEmail(cliente2.getContato().getId());
        try {
            ConexaoBanco.getConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(RealizarNovoEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        usuario.setText("Nome de Usuário - " + this.umCliente.getUsuario());
        senha.setText("Senha - " + "********");
        email.setText("Email - " + emailV);
    }
    
    public VisualizarDadosCliente(){
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JToggleButton();
        alterarEmail = new javax.swing.JToggleButton();
        alterarSenha = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magnoteca");
        setResizable(false);
        getContentPane().setLayout(null);

        voltar.setFont(new java.awt.Font("Centaur", 1, 11)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(570, 390, 76, 34);

        alterarEmail.setFont(new java.awt.Font("Centaur", 0, 11)); // NOI18N
        alterarEmail.setText("Alterar");
        alterarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(alterarEmail);
        alterarEmail.setBounds(410, 230, 70, 29);

        alterarSenha.setFont(new java.awt.Font("Centaur", 0, 11)); // NOI18N
        alterarSenha.setText("Alterar");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(alterarSenha);
        alterarSenha.setBounds(410, 200, 70, 29);

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel1.setText("DADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 50, 90, 28);
        getContentPane().add(cpf);
        cpf.setBounds(200, 130, 170, 30);
        getContentPane().add(nome);
        nome.setBounds(200, 100, 170, 30);
        getContentPane().add(email);
        email.setBounds(200, 240, 170, 30);
        getContentPane().add(usuario);
        usuario.setBounds(200, 160, 170, 30);
        getContentPane().add(senha);
        senha.setBounds(200, 200, 170, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, -10, 85, 290);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        try{
            new PaginaDeAcessoCliente(this.umCliente).setVisible(true);
        } catch (Exception e){
            e.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void alterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaActionPerformed
        new AlterarSenhaDoClienteLogin().setVisible(true);
        
    }//GEN-LAST:event_alterarSenhaActionPerformed

    private void alterarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEmailActionPerformed
        new AlterarEmailDoCliente().setVisible(true);
        
    }//GEN-LAST:event_alterarEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton alterarEmail;
    private javax.swing.JToggleButton alterarSenha;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel usuario;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
}
