/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.GUI;

import br.com.projeto.conexao.ConexaoBanco;
import br.com.projeto.entidades.Funcionario;
import br.com.projeto.interfaces.ContatoDao;
import br.com.projeto.interfaces.FuncionarioDao;
import br.com.projeto.interfacesImpl.ContatoDaoImpl;
import br.com.projeto.interfacesImpl.FuncionarioDaoImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rafael Cardozo
 */
public class VisualizarDadosFuncionarioBibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarDadosFuncionarioBibliotecario
     */
    private String nomedousuario;
    private Funcionario umFuncionario;
    /**
     * Creates new form DadosFun
     */
    public VisualizarDadosFuncionarioBibliotecario(Funcionario umFuncionario){
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
        this.umFuncionario = umFuncionario;
        
        FuncionarioDao funcionarioDao = new FuncionarioDaoImpl(ConexaoBanco.getConnection());
        Funcionario funcionario2 = funcionarioDao.buscarTudoFuncionario(this.umFuncionario.getUsuario());
        ContatoDao contatoDao = new ContatoDaoImpl(ConexaoBanco.getConnection());
        String emailV = contatoDao.buscarEmail(funcionario2.getContato().getId());
        try {
            ConexaoBanco.getConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(RealizarNovoEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        usuario.setText("Nome de Usuário - " + this.umFuncionario.getUsuario());
        senha.setText("Senha - " + "********");
        email.setText("Email - " + emailV);
    }
    
    public VisualizarDadosFuncionarioBibliotecario(){
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src\\Imagens\\images.png");
            setIconImage(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        setSize(678, 489);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JLabel();
        alterarSenha = new javax.swing.JToggleButton();
        alterarEmail = new javax.swing.JToggleButton();
        voltar = new javax.swing.JToggleButton();
        cpf = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(email);
        email.setBounds(130, 270, 260, 30);

        alterarSenha.setFont(new java.awt.Font("Centaur", 0, 11)); // NOI18N
        alterarSenha.setText("Alterar");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(alterarSenha);
        alterarSenha.setBounds(410, 200, 70, 29);

        alterarEmail.setFont(new java.awt.Font("Centaur", 0, 11)); // NOI18N
        alterarEmail.setText("Alterar");
        alterarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(alterarEmail);
        alterarEmail.setBounds(410, 270, 70, 29);

        voltar.setFont(new java.awt.Font("Centaur", 1, 11)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(580, 390, 76, 34);
        getContentPane().add(cpf);
        cpf.setBounds(200, 140, 170, 30);
        getContentPane().add(data);
        data.setBounds(200, 230, 170, 30);
        getContentPane().add(nome);
        nome.setBounds(200, 110, 170, 30);
        getContentPane().add(senha);
        senha.setBounds(130, 200, 260, 30);
        getContentPane().add(usuario);
        usuario.setBounds(130, 170, 260, 30);

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel1.setText("DADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 40, 90, 28);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarcadorBG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, -10, 85, 290);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 380, 320, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaActionPerformed
        new AlterarSenhaDoFuncionarioLogin().setVisible(true);

    }//GEN-LAST:event_alterarSenhaActionPerformed

    private void alterarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEmailActionPerformed
        new AlterarEmailDoFuncionario().setVisible(true);

    }//GEN-LAST:event_alterarEmailActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        try {
            new PaginaDeAcessoFuncionarioBibliotecario(this.umFuncionario).setVisible(true);
        } catch (Exception e) {
            System.out.println("...");
        }
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton alterarEmail;
    private javax.swing.JToggleButton alterarSenha;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel data;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel usuario;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
}
